/* ============================================================ */
/* 01 Basics                                                    */
/* ============================================================ */

// Hello World, running code
// OS X: Cmd Return
// Linux/Windows: Ctrl Return



// Running multiple lines ()



// Clearing the post window
// OS X: Cmd Shift P
// Lin/Win: Ctrl Shift P



// Help
// OS X: Cmd D
// Lin/Win: Ctrl D


// Parts of the IDE



// Comments
/*
Longer
Comments
*/